version: "3.9"

services:
  backend:
    build: ./backend
    container_name: nestjs-backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    restart: always

  frontend:
    build: ./frontend
    container_name: vite-frontend
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - backend
