name: First Demo Action 
on: 
  push: 
    branches: 
      - main

jobs:
  demo-job: 
    runs-on: ubuntu-latest
    steps:
      - run: echo "Action started!"
      
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run a one-line script
        run: echo "Hello, world!"  

      - name: Run a multi-line script
        run: |
          echo "This is a multi-line script"
          echo "It has multiple lines"

      - name: List Files 
        run: ls ${{ github.workspace }}

      - name: Print Github Context 
        env: 
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Action Completed 
        run: echo "Action completed!"
