name: Test Using Mocha

on: [push]

jobs: 
  test:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with: 
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm test

      - name: All Tests Passed
        run: echo "All tests passed"
